### PR TITLE
[APIView] Sanitize text tokens of newlines on ingestion

### LINKED ISSUE #14894: [APIView] Sanitize text tokens that have newlines embedded
See: #14891.

While the "bug" is in the Java parser, we could sanitize the text field of offending tokens to prevent this from happening.

```json
{
                            "Kind": 0,
                            "Value": "\n    This package contains clients and data structures used to make call with Azure Communication Call Automation Service.\n    For this release, see notes - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/communication/azure-communication-callautomation/README.md and https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/communication/azure-communication-callautomation/CHANGELOG.md.\n  ",
                            "HasSuffixSpace": true,
                            "HasPrefixSpace": false,
                            "RenderClasses": [
                                "mavenValue"
  ]
}
```

Here's an example of the offending token, that is passing through newlines, resulting in buggy UI and also causing copilot comments to be attached to the wrong lines.

### PR DESCRIPTION
**Pull request by smw-ms**
resolves: https://github.com/Azure/azure-sdk-tools/issues/14894

### CODE REVIEW

File: src/dotnet/APIView/APIViewUnitTests/CodeFileManagerTests.cs [hunk 1]
```diff
@@ -5,6 +5,7 @@
 using System.Text.Json;
 using System.Text.Json.Serialization;
 using System.Threading.Tasks;
+using APIView;
 using ApiView;
```
Comment (tjprescott) [inline src/dotnet/APIView/APIViewUnitTests/CodeFileManagerTests.cs]: What is going on here? Why are there two namespaces that differ only in casing?

File: src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs [hunk 2]
```diff
@@ -316,5 +319,65 @@ private static void InitializeFromCodeFile(APICodeFileModel file, CodeFile codeF
...
+            if (codeFile.Tokens != null && codeFile.Tokens.Length > 0)
+            {
+                for (int i = 0; i < codeFile.Tokens.Length; i++)
+                {
+                    if (codeFile.Tokens[i].Kind != APIView.CodeFileTokenKind.Whitespace &&
+                        codeFile.Tokens[i].Kind != APIView.CodeFileTokenKind.Newline &&
+                        !string.IsNullOrEmpty(codeFile.Tokens[i].Value))
+                        codeFile.Tokens[i].Value = NormalizeTokenValue(codeFile.Tokens[i].Value);
+                }
+            }
```
Comment (tjprescott) [inline src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs]: We should *not* be updating for the legacy format. The goal is to deprecate the old format, not add workarounds and patches for it.

For this case, we should only be looking at `TokenKind.Text`

**Review by tjprescott — CHANGES_REQUESTED** [review]
We don't want to extend this fix to legacy formats.

File: src/dotnet/APIView/APIViewUnitTests/CodeFileManagerTests.cs (hunk 1 above)
Comment (smw-ms) [reply src/dotnet/APIView/APIViewUnitTests/CodeFileManagerTests.cs]: `ApiVIew` is the namespace for the CodeFile class. `APIView` contains the model CodeFileTokenKind. With my new updates, it removes any changes related to the legacy version, so will no longer need to use `APIView`

**Review by tjprescott — APPROVED** [review]
