### PR TITLE
Poll LRO Endpoint from Background Service

### LINKED ISSUE #11002: [APIView] Feedback on Copilot Review UX
**PROBLEM**
1. When the generate review button is pressed, it animates like it is synchronous and still "times out" and displays a failure message. However, it is using the LRO endpoints and polls, and if the review actually succeeds on the backend, and the comments appear when the page is refreshed. This is massively confusing.
Image

2. Once the review "fails" you can click the generate button again, leading to multiple jobs being created on the backend unnecessarily.
3. Once a review has been completed successfully, the button changes to say "Regenerate copilot review". But this implies it will get rid of old comments, which it doesn't do.

**SOLUTION**
1. "Regenerate copilot review" text remain "Generate copilot review". You are just requesting another review. 
2. We should get rid of the UX that shows the animated dot that makes it seem like a review is synchronous. We should NOT have the red "failed to generate comments" pop-up appear at all.

Open to discuss what the UX should be here.

### LINKED ISSUE #11006: [APIView] APIView drops comments from Copilot instead of posting them on large review
https://spa.apiview.dev/review/899e9843d9e6414896e189da46b1e16c?activeApiRevisionId=5159ebbc936a43159e77ee18fc78a508

Copilot was run on this very large APIView.

Logs show that it ran successfully for 32 minutes and produced 200 comments. However, APIView did not post any of the comments. They were lost.

### PR DESCRIPTION
**Pull request by chidozieononiwu**
- Poll LRO endpoint from BackgroundService
Fixes #11006
Fixes #11002

### CODE REVIEW

File: src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs [hunk 1]
```diff
@@ -155,8 +155,8 @@ public async Task<ActionResult<int>> GenerateAIReview(string reviewId, [FromQuer
         {
             try
             {
-                var violations = await _reviewManager.GenerateAIReview(User, reviewId, activeApiRevisionId, diffApiRevisionId);
-                return new LeanJsonResult(violations, StatusCodes.Status200OK);
+                await _reviewManager.GenerateAIReview(User, reviewId, activeApiRevisionId, diffApiRevisionId);
```
Comment (AlitzelMendez) [inline src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs:196]: is this the call that is taking a long time? do we need to await for it? speciallly if we are returning just the `Accepted`

File: src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+            while (!stoppingToken.IsCancellationRequested)
+            {
+                if (_pollingJobQueueManager.TryDequeue(out AIReviewJobInfoModel jobInfo))
+                {
+                    var task = Task.Run(async () =>
+                    {
+                        try
+                        {
+                            var client = _httpClientFactory.CreateClient();
+                            var poolUrl = $"{_copilotEndpoint}/api-review/{jobInfo.JobId}";
```
Comment (praveenkuttappan) [inline src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs]:
```suggestion
                            var pollUrl = $"{_copilotEndpoint}/api-review/{jobInfo.JobId}";
```

File: src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+                            var poller = new Poller();
+                            var result = await poller.PollAsync(
+                                operation: async () =>
+                                {
+                                    var response = await client.GetAsync(poolUrl);
```
Comment (praveenkuttappan) [inline src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs]:
```suggestion
                                    var response = await client.GetAsync(pollUrl);
```

File: src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+                        catch (Exception e)
+                        {
+                            jobInfo.APIRevision.CopilotReviewInProgress = false;
+                            await _apiRevisionsManager.UpdateAPIRevisionAsync(jobInfo.APIRevision);
+                            throw new Exception($"Copilot Failed: {e.Message}");
+                        }
+
+                    }, stoppingToken);
+                }
+                await Task.Delay(1000, stoppingToken);
```
Comment (praveenkuttappan) [inline src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs:138]: Does this need to be this aggressive to run every 1 second?

File: src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+                                    commentText.AppendLine($"See: https://azure.github.io/azure-sdk/{id}");
+                                }
+                                commentModel.ResolutionLocked = false;
+                                commentModel.CreatedBy = "azure-sdk";
+                                commentModel.CommentText = commentText.ToString();
+
+                                await _commentsRepository.UpsertCommentAsync(commentModel);
+                                jobInfo.APIRevision.HasAutoGeneratedComments = true;
+                            }
+                            jobInfo.APIRevision.CopilotReviewInProgress = false;
```
Comment (praveenkuttappan) [inline src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs:114]: How is it handled now if two approvers are trying to generate review comments? Is it blocked in UI when it is in progress?

Comment (praveenkuttappan) [reply src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs:114]: Also what happens if server is restarted while a request is in progress? I think revision will be stuck in in-progress state. if Job request saved to DB or is it only in memory?

**Review by praveenkuttappan — APPROVED** [review]
Couple of questions. Otherwise looks fine to me.

File: src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs (hunk 5 above)
Comment (tjprescott) [reply src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs:114]: The UX should be that you can't request a new copilot review while a job is in progress. Only once it has succeeded or failed should you be able to request another. 

+1 on the question about in-progress job state.

File: src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs (hunk 1 above)
Comment (chidozieononiwu) [reply src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs:196]: I think it should still be awaited. The actual polling is offloaded to a background service

**Review by tjprescott — APPROVED** [review]
