### PR TITLE
General codesnippet-maven-plugin Changes

### LINKED ISSUE #2142: Updates to codesnippet-maven-plugin
Add the following updates to `codesnippet-maven-plugin`:

- [ ] Fail on missing codesnippet tag, default to true
- [ ] Enable validation of codesnippet length
- [x] Fix skipping the run of the plugin - caused by https://issues.apache.org/jira/browse/MNG-4979

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #2142 

This PR contains general updates for the `codesnippet-maven-plugin` used in the Azure SDKs.

- Adds support to not fail on errors.
- Now validates the maximum line length allowed for codesnippets.
- Adds a `codesnippet` prefix to all configuration parameters.

### CODE REVIEW

File: packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetMissingError.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+    /**
+     * Creates a missing codesnippet error.
+     *
+     * @param snippetId The ID of the codesnippet.
+     * @param snippetLocation Where the codesnippet was being referenced.
+     */
+    CodesnippetMissingError(String snippetId, Path snippetLocation) {
+        super(snippetId, snippetLocation);
+    }
+}
```
Comment (conniey) [inline packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetMissingError.java:21]: nit: missing new line

File: packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/VerifyResult.java [hunk 2]
```diff
@@ -9,11 +9,29 @@
...
+
+    /**
+     * Gets the identifier of the codesnippet that was verified.
+     *
+     * @return The identifier of the codesnippet that was verified.
+     */
+    public String getSnippetId() {
+        return snippetId;
     }
 }
```
Comment (conniey) [inline packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/VerifyResult.java:37]: nit: missing new line.

**Review by conniey — APPROVED** [review]
lgtm
