### PR TITLE
[tsp-client] Normalize tsp-location.yaml directories before processing

### LINKED ISSUE #8382: [tsp-client] failed to parse out the project name, throw 'cannot find project name' error
in tsp-client, it try to parse out the project name from `directory` in tsp-location.yaml, it failed to parse out the project name because it does not trim out the `/` or `\` at the end of the string, e.g. directory: specification/ai/HealthInsights/HealthInsights.OncoPhenotype/

https://github.com/Azure/azure-sdk-tools/blob/a92e1a992e45191fe9dc3684d88049f1645d9d42/tools/tsp-client/src/index.ts#L201

expected:
We need to parse out project name in all path scenarios
- separate by `/` or `\`
- end with `/` or `\`

### PR DESCRIPTION
**Pull request by catalinaperalta**
Fixes #8382

### CODE REVIEW

File: tools/tsp-client/src/fs.ts [hunk 1]
```diff
@@ -59,3 +64,8 @@ export async function getEmitterFromRepoConfig(emitterPath: string): Promise<str
   }
   throw new Error("Could not find emitter package");
 }
+
+export function normalizeDirectory(directory: string): string {
+    let normalizedDir = normalizePath(directory);
```
Comment (joheredi) [inline tools/tsp-client/src/fs.ts:69]: nit, I think this can be a const

**Review by joheredi — APPROVED** [review]

**Review by timotheeguerin — APPROVED** [review]
