### PR TITLE
[rust-api-parser] Fix duplicate line ID generation

### LINKED ISSUE #11860: [Rust APIView] Rust parser generates duplicate line IDs causing Copilot review failures
The Rust parser is generating duplicate line IDs, which is causing Copilot review requests to fail immediately with no diagnostics. 

This issue was discovered when testing the [azure_security_keyvault_secrets](https://spa.apiviewstagingtest.com/review/bd8ec289970e4edc8bacf9a1489ebc41?activeApiRevisionId=cc7e32d797a546c493919929e22eeb1e) package.

The impacted line id is: `root_mod_azure_security_keyvault_secrets_ResourceIdimpl_TryFrom_Url_for_ResourceId`

### PR DESCRIPTION
**Pull request by HarshaNalluru**
Fixes #11860 by implementing comprehensive duplicate line ID detection and prevention in the Rust API parser.

## Problem
The Rust API parser was generating duplicate line IDs, particularly for similar trait implementations like `impl TryFrom<&Url>` and `impl TryFrom<Url>`, causing Copilot reviews to fail immediately without diagnostics.

## Solution
- Implemented semantic replacements that preserve meaningful distinctions (e.g., `&` → `ref_`, `<>` → `_of_/_end_`)
- Improved external re-export handling: Use full paths instead of just item names to prevent collisions
- **Defensive duplicate detection**: Added automatic counter-based fixing with comprehensive validation before JSON serialization
- Explained why deduplication is needed for re-exports and complex type scenarios

## Results
<details>
<summary>✅ Batch Processing Results - All 21 Packages Successfully Processed</summary>

```bash
@HarshaNalluru ➜ .../tools/apiview/parsers/rust-api-parser (harshan/fix-dedup-lineids) $ bash [process-all-packages.sh](http://_vscodecontentref_/0)
🚀 Processing all Rust API reports with duplicate line ID fixes...
📁 Input folder: ./inputs/
📁 Output folder: ./outputs/

📦 Processing: azure_core
   Input:  [azure_core.rust.json](http://_vscodecontentref_/1)
   Output: [azure_core.json](http://_vscodecontentref_/2)
The exported API surface has been successfully saved to './outputs/azure_core.json'
   ✅ SUCCESS: Generated [azure_core.json](http://_vscodecontentref_/3)

📦 Processing: azure_core_amqp
   Input:  [azure_core_amqp.rust.json](http://_vscodecontentref_/4)
   Output: [azure_core_amqp.json](http://_vscodecontentref_/5)
The exported API surface has been successfully saved to './outputs/azure_core_amqp.json'
   ✅ SUCCESS: Generated [azure_core_amqp.json](http://_vscodecontentref_/6)

📦 Processing: azure_core_macros
   Input:  [azure_core_macros.rust.json](http://_vscodecontentref_/7)
   Output: [azure_core_macros.json](http://_vscodecontentref_/8)
The exported API surface has been successfully saved to './outputs/azure_core_macros.json'
   ✅ SUCCESS: Generated [azure_core_macros.json](http://_vscodecontentref_/9)

📦 Processing: azure_core_opentelemetry
   Input:  [azure_core_opentelemetry.rust.json](http://_vscodecontentref_/10)
   Output: [azure_core_opentelemetry.json](http://_vscodecontentref_/11)
The exported API surface has been successfully saved to './outputs/azure_core_opentelemetry.json'
   ✅ SUCCESS: Generated [azure_core_opentelemetry.json](http://_vscodecontentref_/12)

📦 Processing: azure_core_test
   Input:  [azure_core_test.rust.json](http://_vscodecontentref_/13)
   Output: [azure_core_test.json](http://_vscodecontentref_/14)
The exported API surface has been successfully saved to './outputs/azure_core_test.json'
   ✅ SUCCESS: Generated [azure_core_test.json](http://_vscodecontentref_/15)

📦 Processing: azure_core_test_macros
   Input:  [azure_core_test_macros.rust.json](http://_vscodecontentref_/16)
   Output: [azure_core_test_macros.json](http://_vscodecontentref_/17)
The exported API surface has been successfully saved to './outputs/azure_core_test_macros.json'
   ✅ SUCCESS: Generated [azure_core_test_macros.json](http://_vscodecontentref_/18)

📦 Processing: azure_data_cosmos
   Input:  [azure_data_cosmos.rust.json](http://_vscodecontentref_/19)
   Output: [azure_data_cosmos.json](http://_vscodecontentref_/20)
The exported API surface has been successfully saved to './outputs/azure_data_cosmos.json'
   ✅ SUCCESS: Generated [azure_data_cosmos.json](http://_vscodecontentref_/21)

📦 Processing: azure_identity
   Input:  [azure_identity.rust.json](http://_vscodecontentref_/22)
   Output: [azure_identity.json](http://_vscodecontentref_/23)
The exported API surface has been successfully saved to './outputs/azure_identity.json'
   ✅ SUCCESS: Generated [azure_identity.json](http://_vscodecontentref_/24)

📦 Processing: azure_messaging_eventhubs
   Input:  [azure_messaging_eventhubs.rust.json](http://_vscodecontentref_/25)
   Output: [azure_messaging_eventhubs.json](http://_vscodecontentref_/26)
The exported API surface has been successfully saved to './outputs/azure_messaging_eventhubs.json'
   ✅ SUCCESS: Generated [azure_messaging_eventhubs.json](http://_vscodecontentref_/27)

📦 Processing: azure_messaging_eventhubs_checkpointstore_blob
   Input:  [azure_messaging_eventhubs_checkpointstore_blob.rust.json](http://_vscodecontentref_/28)
   Output: [azure_messaging_eventhubs_checkpointstore_blob.json](http://_vscodecontentref_/29)
The exported API surface has been successfully saved to './outputs/azure_messaging_eventhubs_checkpointstore_blob.json'
   ✅ SUCCESS: Generated [azure_messaging_eventhubs_checkpointstore_blob.json](http://_vscodecontentref_/30)

📦 Processing: azure_messaging_servicebus
   Input:  [azure_messaging_servicebus.rust.json](http://_vscodecontentref_/31)
   Output: [azure_messaging_servicebus.json](http://_vscodecontentref_/32)
The exported API surface has been successfully saved to './outputs/azure_messaging_servicebus.json'
   ✅ SUCCESS: Generated [azure_messaging_servicebus.json](http://_vscodecontentref_/33)

📦 Processing: azure_security_keyvault_certificates
   Input:  [azure_security_keyvault_certificates.rust.json](http://_vscodecontentref_/34)
   Output: [azure_security_keyvault_certificates.json](http://_vscodecontentref_/35)
The exported API surface has been successfully saved to './outputs/azure_security_keyvault_certificates.json'
   ✅ SUCCESS: Generated [azure_security_keyvault_certificates.json](http://_vscodecontentref_/36)

📦 Processing: azure_security_keyvault_keys
   Input:  [azure_security_keyvault_keys.rust.json](http://_vscodecontentref_/37)
   Output: [azure_security_keyvault_keys.json](http://_vscodecontentref_/38)
The exported API surface has been successfully saved to './outputs/azure_security_keyvault_keys.json'
   ✅ SUCCESS: Generated [azure_security_keyvault_keys.json](http://_vscodecontentref_/39)

📦 Processing: azure_security_keyvault_secrets
   Input:  [azure_security_keyvault_secrets.rust.json](http://_vscodecontentref_/40)
   Output: [azure_security_keyvault_secrets.json](http://_vscodecontentref_/41)
The exported API surface has been successfully saved to './outputs/azure_security_keyvault_secrets.json'
   ✅ SUCCESS: Generated [azure_security_keyvault_secrets.json](http://_vscodecontentref_/42)

📦 Processing: azure_storage_blob
   Input:  [azure_storage_blob.rust.json](http://_vscodecontentref_/43)
   Output: [azure_storage_blob.json](http://_vscodecontentref_/44)
The exported API surface has been successfully saved to './outputs/azure_storage_blob.json'
   ✅ SUCCESS: Generated [azure_storage_blob.json](http://_vscodecontentref_/45)

📦 Processing: azure_storage_common
   Input:  [azure_storage_common.rust.json](http://_vscodecontentref_/46)
   Output: [azure_storage_common.json](http://_vscodecontentref_/47)
The exported API surface has been successfully saved to './outputs/azure_storage_common.json'
   ✅ SUCCESS: Generated [azure_storage_common.json](http://_vscodecontentref_/48)

📦 Processing: azure_template
   Input:  [azure_template.rust.json](http://_vscodecontentref_/49)
   Output: [azure_template.json](http://_vscodecontentref_/50)
The exported API surface has been successfully saved to './outputs/azure_template.json'
   ✅ SUCCESS: Generated [azure_template.json](http://_vscodecontentref_/51)

📦 Processing: azure_template_core
   Input:  [azure_template_core.rust.json](http://_vscodecontentref_/52)
   Output: [azure_template_core.json](http://_vscodecontentref_/53)
The exported API surface has been successfully saved to './outputs/azure_template_core.json'
   ✅ SUCCESS: Generated [azure_template_core.json](http://_vscodecontentref_/54)

📦 Processing: typespec
   Input:  [typespec.rust.json](http://_vscodecontentref_/55)
   Output: [typespec.json](http://_vscodecontentref_/56)
The exported API surface has been successfully saved to './outputs/typespec.json'
   ✅ SUCCESS: Generated [typespec.json](http://_vscodecontentref_/57)

📦 Processing: typespec_client_core
   Input:  [typespec_client_core.rust.json](http://_vscodecontentref_/58)
   Output: [typespec_client_core.json](http://_vscodecontentref_/59)
The exported API surface has been successfully saved to './outputs/typespec_client_core.json'
   ✅ SUCCESS: Generated [typespec_client_core.json](http://_vscodecontentref_/60)

📦 Processing: typespec_macros
   Input:  [typespec_macros.rust.json](http://_vscodecontentref_/61)
   Output: [typespec_macros.json](http://_vscodecontentref_/62)
The exported API surface has been successfully saved to './outputs/typespec_macros.json'
   ✅ SUCCESS: Generated [typespec_macros.json](http://_vscodecontentref_/63)

📊 PROCESSING SUMMARY
=====================
Total packages:      21
Successful:          21
Failed:              0

🎉 All packages processed successfully!
✅ All outputs are available in the ./outputs/ directory
✅ Duplicate line ID fixes have been applied to all packages


## Testing
- Processed all 21 Azure SDK Rust packages with 100% success rate
- Created comprehensive batch processing script for validation
- Added diagnostic logging for duplicate analysis and root cause investigation

</details>

### CODE REVIEW

File: tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts [hunk 1]
```diff
@@ -21,6 +65,99 @@ function postProcessLineIdMap(reviewLines: ReviewLine[], updatedLineIdMap: Map<s
...
+        const counter = (lineIdCounters.get(baseId) || 1) + 1;
+        lineIdCounters.set(baseId, counter);
+        finalLineId = `${baseId}_${counter}`;
+        
+        // Keep incrementing until we find a unique ID
+        while (usedLineIds.has(finalLineId)) {
+          const newCounter = lineIdCounters.get(baseId)! + 1;
+          lineIdCounters.set(baseId, newCounter);
+          finalLineId = `${baseId}_${newCounter}`;
+        }
```
[the remark this answers is not in the document]
Comment (HarshaNalluru) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: there won't be many duplicates; mainly the re-exports internal and external

File: tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts [hunk 2]
```diff
@@ -21,6 +65,99 @@ function postProcessLineIdMap(reviewLines: ReviewLine[], updatedLineIdMap: Map<s
   }
 }
 
+/**
+ * Ensures all line IDs are unique by automatically appending counters to duplicates.
+ * This is a defensive measure to catch any edge cases not handled by sanitization.
+ * @param reviewLines The review lines to validate and fix
+ */
```
Comment (tjprescott) [inline tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: I think it would make more sense to simply have the parser fail if, after sanitization, you still have duplicate line IDs. This immediately let's you know that there's an edge case you don't have covered.

If you do this, you guarantee the parser won't fail, but you may end up with unexpected behavior in APIView. That will then result in more investigation on our part just to figure out that "it's a bug in the parser".

Comment (HarshaNalluru) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: I've looked at the instances and these are essentially the re-exports that should point to the same instance anyway, through NavigateToLineId refs, they'll all come back to the same linedId.

But I get you, I'll remove this piece and rather throw, even if it means more computations to verify the recursive lineids.
Thanks!

File: tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts [hunk 3]
```diff
@@ -3,6 +3,50 @@ import { ReviewLine } from "../models/apiview-models";
...
+    .replace(/:/g, "_")   // colons to underscores
+    .replace(/,/g, "_")   // commas to underscores
+    .replace(/\(/g, "_")  // parentheses
+    .replace(/\)/g, "_")
+    .replace(/\[/g, "_")  // brackets
+    .replace(/\]/g, "_")
+    .replace(/\{/g, "_")  // braces
+    .replace(/\}/g, "_")
+    .replace(/'/g, "_lifetime_") // lifetime parameters
+    .replace(/\$/g, "_dollar_")  // macro variables
```
Comment (heaths) [inline tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts:90]: Speaking of macros, do attribute macros get a line ID? If so, you'll also need to handle `!` and `#`. You already have `[` and `]`, but I would use names like `_exclamation_` and `_hash_` or something.

File: tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts [hunk 4]
```diff
@@ -3,6 +3,50 @@ import { ReviewLine } from "../models/apiview-models";
...
+    .replace(/-/g, "_dash_")     // preserve dashes for crate names
+    // Clean up multiple consecutive underscores
+    .replace(/_+/g, "_")
+    // Remove leading/trailing underscores
+    .replace(/^_+|_+$/g, "");
```
[the remark this answers is not in the document]
Comment (heaths) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts:95]: Maybe a good suggestion, though I wonder if the perf hit of a regex is worth an O(n) repeated is any worse.

**Review by heaths — COMMENTED** [review]
Probably best for Travis or someone more familiar with APIView to sign off, but I did provide a suggestion about symbol translation, if it matters.

File: tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts (hunk 2 above)
Comment (tjprescott) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: Can you give an example of a re-export? I'm not familiar with Go.

Comment (HarshaNalluru) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: Update:
Example of a re-export
image
image

The bug is that these have the same line-id. Current API View rendering links them to the same line (which is not the ideal way to represent the linking).
- Current recursive parsing logic doesn't assume any links/references, if there are any links/references, they get automatically cross referenced through the current API View rendering as they both have the same line ID.

I'm updating this to link/reference through NavigateToLineId instead and more checks where the LineId is set to not have duplicates, this should resolve the issue without the need for hotfixes in the end.

Comment (tjprescott) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: Preface: I don't know Rust 😄 

Could you use the fully qualified name in the second case to disambiguate? `typespec_client_core.http.headers.HeaderValue` vs the plain `HeaderValue`?

Comment (HarshaNalluru) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: Yes, that's the intent of the fix as well, and linking them through NavigateToId.

Comment (heaths) [reply tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts]: FWIW, in Rust we re-export a lot of types. All types in `typespec` are re-exported from `typespec_client_core`, which adds types, and all those types are re-exported in `azure_core`. This is common in Rust - though maybe not to this degree because we're having to support "unbranded".

I don't know how or even if that should affect APIView, but keep in mind when you see a type `Foo` in something like `typespec_client_core`, it should be in `azure_core` with the same module path (sans crate name, which comprises the root module).
