### PR TITLE
fix(.net analyzer): ignore property bag with `Options` suffix

### LINKED ISSUE #7247: [bug][.net analyzer] ignore property bag class with suffix `Options`
## Problem

In [AZC0030](https://github.com/Azure/azure-sdk-tools/blob/41c4ad12414f0aaa2b679bee62be7a89a61ee3c0/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs#L21), we will report a warning if a model class name ends with `Options`. However, our property bag class will have an `Options` suffix. That causes false alerts, like https://github.com/Azure/azure-sdk-for-net/pull/39653/checks?check_run_id=18337868902

> sdk/integrationspaces/Azure.ResourceManager.IntegrationSpaces/src/Generated/Models/BusinessProcessCollectionGetAllOptions.cs(14,26): Error AZC0030: Model name 'BusinessProcessCollectionGetAllOptions' ends with 'Options'. Suggest to rename it to 'BusinessProcessCollectionGetAllConfig' or any other appropriate name.

`BusinessProcessCollectionGetAllOptions` is a property bag. We should ignore such cases in AZC0030

### PR DESCRIPTION
**Pull request by archerzz**
- change `GeneralSuffixAnalyzer` to ignore model classes with `Options` suffix if there is no serialization code
  - Property bag model classes do not have any serialization code
- add test cases

fix #7247

### CODE REVIEW

**Comment by archerzz** [comment]
- Tried on the PR which reported the issue. The fix works fine: https://github.com/Azure/azure-sdk-for-net/pull/39653
- Preview PR on `azure-sdk-for-net`: https://github.com/Azure/azure-sdk-for-net/pull/39791

File: src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs [hunk 1]
```diff
@@ -18,11 +18,41 @@ public class GeneralSuffixAnalyzer : SuffixAnalyzerBase
...
+            if (symbol.Name.EndsWith("Options") && !SupportSerialization(symbol))
+                return true;
+
+            return false;
+        }
+
+        private bool SupportSerialization(INamedTypeSymbol symbol)
+        {
+            // if it has serialization method: `IUtf8JsonSerializable.Write`, e.g. ": IUtf8JsonSerializable"
+            if (symbol.Interfaces.Any(i => i.Name is "IUtf8JsonSerializable"))
```
Comment (ArthurMa1978) [inline src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs:40]: Will this be changed after applying the new model serialization?

File: src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs [hunk 2]
```diff
@@ -18,11 +18,41 @@ public class GeneralSuffixAnalyzer : SuffixAnalyzerBase
...
+                return true;
+
+            // if it has deserialization method: static <T> Deserialize<T>(JsonElement element)
+            if (symbol.GetMembers($"Deserialize{symbol.Name}").Any(m => m is IMethodSymbol methodSymbol &&
+                methodSymbol is { IsStatic: true, ReturnType: INamedTypeSymbol symbol, Parameters.Length: 1 } &&
+                methodSymbol.Parameters[0].Type.Name is "JsonElement"))
+                return true;
+
+            // if it has public serialization: IJsonModel<T>
```
Comment (m-nash) [inline src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs:49]: remove this and open an issue to follow behind the MRW work

**Review by m-nash — APPROVED** [review]

File: src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs (hunk 1 above)
Comment (archerzz) [reply src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs:40]: > Will this be changed after applying the new model serialization?

@ArthurMa1978 Yes. The check on `IJsonModel<T>` is for that purpose.

File: src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs (hunk 2 above)
Comment (archerzz) [reply src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs]: > remove this and open an issue to follow behind the MRW work

@m-nash Filed #7257 for follow-up work.
